language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t swistek/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true swistek/docker-react npm run test

after_success:
  - docker build -t swistek/multi-client ./client
  - docker build -t swistek/multi-nginx ./nginx
  - docker build -t swistek/multi-server ./server
  - docker build -t swistek/multi-wroker ./wroker
